import:
    - "%root_dir%/app/parameters.yml"

debug: true
mode: "development"

# Paths
app_dir:        "%root_dir%/app"
data_dir:       "%root_dir%/data"
cache_dir:      "%data_dir%/cache"
migration_dir:  "%app_dir%/migrations"
seed_dir:       "%app_dir%/seeds"

# Logging
log.enabled: true
log.level:   8
log_dir:     "%data_dir%/log"

# Routes
routes:
  - "Dime\\Server\\Controller\\ResourceController"
  - "Dime\\Server\\Controller\\ParseController"
  - "Dime\\Server\\Controller\\MaintenanceController"
  - "Dime\\Server\\Controller\\DocController"

# Api
api:
  prefix: "/api"
  version: 1
  headers:
    Content-Type: "application/json; charset=utf-8"
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Methods: "GET,POST,PUT,DELETE"
  resources:
    activity:
      model: "Dime\\Server\\Model\\Activity"
      with:
        - "customer"
        - "project"
        - "service"
        - "timeslices"
        - "tags"
      filter: ~
    customer:
      model: "Dime\\Server\\Model\\Customer"
      with: ~
      filter: ~
    project:
      model: "Dime\\Server\\Model\\Project"
      with:
        - "customer"
      filter: ~
    service:
      model: "Dime\\Server\\Model\\Service"
      with: ~
      filter: ~
    setting:
      model: "Dime\\Server\\Model\\Setting"
      with: ~
      filter: ~
    tag:
      model: "Dime\\Server\\Model\\Tag"
      with: ~
      filter: ~
    timeslice:
      model: "Dime\\Server\\Model\\Timeslice"
      with:
        - "activity"
        - "tags"
      filter: ~

doc:
  prefix: "/doc"

auth:
  realm: "Dime Timetracker"
  user:   "Dime\\Server\\Model\\User"
  access: "Dime\\Server\\Model\\Access"
