#!/usr/bin/env php
<?php

define('ROOT_DIR', realpath(dirname(__FILE__) . '/../'));
$loader = require_once ROOT_DIR . '/vendor/autoload.php';
$config = require_once ROOT_DIR . '/app/config.php';

$cli = new \Symfony\Component\Console\Application('Dime Timetracker');
$cli->setCatchExceptions(true);

$cli->addCommands([
    new Dime\Server\Command\InstallCommand(),
    new Dime\Server\Command\UpgradeCommand(),
]);

$cli->run();
