#!/usr/bin/env php
<?php

define('ROOT_DIR', realpath(dirname(__FILE__) . '/../'));
$loader = require_once ROOT_DIR . '/vendor/autoload.php';
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader([$loader, 'loadClass']);



$config = require_once ROOT_DIR . '/app/config.php';


use Jgut\Slim\Doctrine\EntityManagerBuilder;

$em = EntityManagerBuilder::build($config['settings']['doctrine']);

$configuration = new \Doctrine\DBAL\Migrations\Configuration\Configuration($em->getConnection());
$configuration->setMigrationsNamespace($config['settings']['migrations']['namespace']);
$configuration->setMigrationsDirectory($config['settings']['migrations']['directory']);
$configuration->setMigrationsTableName($config['settings']['migrations']['table_name']);

$helpers = new Symfony\Component\Console\Helper\HelperSet([
    'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($em->getConnection()),
    'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper($em),
    'dialog' => new Symfony\Component\Console\Helper\QuestionHelper(),
    'configuration' => new \Doctrine\DBAL\Migrations\Tools\Console\Helper\ConfigurationHelper($em->getConnection(), $configuration)
]);

$cli = new \Symfony\Component\Console\Application('Dime Timetracker');
$cli->setCatchExceptions(true);
$cli->setHelperSet($helpers);
$cli->addCommands([
    new Dime\Server\Command\InstallCommand(),
    new Dime\Server\Command\UpgradeCommand()
]);

$cli->run();
